# The path to the directory where all generated files will be written to. This
# can be an absolute path starting with a slash, but it can also be path
# relative to the site directory.
# we have changed this to be a frankensite
output_dir: public

index_filenames: [ 'index.html', 'index.xml']
deploy:
  default:
    dst: hipeland.org:/var/sites/whatever.hipeland.org
